% University of Surrey
%
% This file is part of TLD.
%

function M = img_blur(M,sigma)
% Blures gray scale image with gaussian kernel. 

if nargin==1
    sigma = 1.5;
end

csize = 6*sigma;

shift = (csize - 1)/2;

% h = FSPECIAL('gaussian',csize,sigma);
h = fspecial('gaussian',csize,sigma);

% EDIT(zori) get rid of the warnings generated by the following
% M = conv2(M,h);
% M = M(1+shift:end-shift,1+shift:end-shift); % shift would (sometimes) be, e.g. 5.5
M = conv2(double(M),h);
M = M(1+ceil(shift):end-floor(shift),1+ceil(shift):end-floor(shift));
M = uint8(M);
